server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://127.0.0.1:3306/sellSystem?useUnicode=true&characterEncoding=utf-8
  jpa:
    properties:
     hibernate:
        format_sql: true
        show_sql: true
    generate-ddl: true


